                    !byte 0x07
                    ror 0xa9,x
                    asl 0x59
                    !byte 0x7f
                    cmp 0x04
                    !byte 0x3b
                    !byte 0x54
                    !byte 0x83
                    lda 0xe3c0
                    !byte 0x02
                    asl 0x422a,x
                    lsr 0x60,x
                    adc (0x81),y
                    !byte 0x8f
                    sta 0x00,x
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
