datenschrott06:
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x00,x)
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    ora (0x01,x)
                    ora (0x00,x)
                    bpl 0x281c
                    !byte 0x0c
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x285d
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    bpl 0x2877
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x04
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x04
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x04
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x04
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x03
                    !byte 0x04
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x04
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    bpl 0x28c4
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    bpl 0x28df
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x02,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    bpl 0x293a
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x03
                    ora (0x10,x)
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x00,x)
                    ora (0x01,x)
                    ora (0x00,x)
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    ora (0x00,x)
                    ora (0x00,x)
                    ora (0x00,x)
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x00,x)
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    ora (0x00,x)
                    !byte 0x00
                    ora (0x00,x)
                    ora (0x00,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x00,x)
                    ora (0x00,x)
                    !byte 0x00
                    bpl 0x2987
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x02,x)
                    !byte 0x00
                    !byte 0x02
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x06,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x07
                    ora (0x01,x)
                    !byte 0x00
                    bpl 0x29c0
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    ora (0x00,x)
                    ora (0x01,x)
                    ora (0x06,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x02,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x07
                    ora (0x01,x)
                    ora (0x00,x)
                    ora (0x02,x)
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    asl 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x07
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x01,x)
                    asl 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x02,x)
                    !byte 0x00
                    !byte 0x02
                    ora (0x10,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x07
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora 0x0100
                    ora (0x01,x)
                    !byte 0x00
                    ora 0x0100
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x10,x)
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora 0x0100
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora 0x0100
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    ora (0x03,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora 0x0000
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    ora 0x0000
                    bpl 0x2a65
                    ora (0x01,x)
                    !byte 0x00
                    ora 0x0100
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    bpl 0x2a7f
                    !byte 0x02
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x02
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x02
                    !byte 0x00
                    bpl 0x2a8d
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    bpl 0x2aa7
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    bpl 0x2ac1
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x02
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x02
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2ad9
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x0b
                    bpl 0x2ae7
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x0c
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora 0x00
                    !byte 0x0b
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x00,x)
                    bpl 0x2b35
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x08,x)
                    asl
                    ora #0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    bpl 0x2b4f
                    !byte 0x00
                    !byte 0x00
                    ora (0x08,x)
                    asl
                    ora #0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    php
                    asl
                    ora #0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    php
                    asl
                    ora #0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    php
                    asl
                    ora #0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2b83
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    php
                    asl
                    ora #0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    php
                    asl
                    ora #0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    php
                    asl
                    ora #0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    bpl 0x2bb7
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x03
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2c06
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x03
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    bpl 0x2c46
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2c54
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x00,x)
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x02,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    ora (0x02,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2cae
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    bpl 0x2cbc
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    ora (0x02,x)
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x0b
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    ora (0x00,x)
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x0c
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    ora (0x00,x)
                    !byte 0x00
                    ora 0x0000
                    !byte 0x00
                    !byte 0x00
                    ora 0x0000
                    !byte 0x00
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2d0f
                    !byte 0x00
                    ora 0x0000
                    ora (0x10,x)
                    !byte 0x00
                    !byte 0x00
                    ora 0x0000
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x03
                    ora (0x01,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora 0x0000
                    !byte 0x00
                    ora 0x0000
                    !byte 0x00
                    ora (0x00,x)
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x00
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x01,x)
                    ora (0x00,x)
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    bpl 0x2d57
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    bpl 0x2d72
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x03
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    asl
                    asl
                    asl
                    asl
                    asl
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    bpl 0x2dbf
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    asl
                    asl
                    asl
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2dcd
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    asl
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    asl
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    asl
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    asl
                    asl
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    asl
                    asl
                    asl
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    asl
                    asl
                    asl
                    asl
                    asl
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    asl
                    asl
                    asl
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x03
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    bpl 0x2e34
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2e76
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x03
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    bpl 0x2e8f
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    bpl 0x2ef7
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    bpl 0x2f12
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    bpl 0x2f5f
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    asl 0x000f
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x02
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00

                    !byte 0x00
                    !byte 0x00
                    !byte 0x02
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
datenschrott06_ende:!byte 0x00
