; definitiv kein Schrott
; Aber z.T. um ein Byte geshifted

                    rts
                    !byte 0xff
                    cmp #0xdf
                    beq 0x39a5
                    inc 0x0a
                    lda (0xa7),y
                    jmp 0x38b7
                    asl 0x03
                    !byte 0x12
                    and (0x03,x)
                    !byte 0x03
                    !byte 0x12
                    and (0x03,x)
                    !byte 0x03
                    ora 0x21,x
                    !byte 0x03
                    !byte 0x03
                    !byte 0x0f
                    and (0x15,x)
                    asl 0x0606,x
                    asl 0x03
                    !byte 0x12
                    and (0x03,x)
                    !byte 0x03
                    ora #0x21
                    !byte 0x03
                    !byte 0x03
                    !byte 0x12
                    and (0x03,x)
                    !byte 0x03
                    !byte 0x0c
                    and (0x03,x)
                    !byte 0x03
                    !byte 0x12
                    and (0x0c,x)
                    !byte 0x03
                    !byte 0x0c
                    jsr 0x030c
                    !byte 0x0c
                    and (0x0c,x)
                    !byte 0x03
                    ora #0x15
                    !byte 0x03
                    !byte 0x03
                    asl 0x21
                    !byte 0x03
                    !byte 0x03
                    !byte 0x03
                    and (0x06,x)
                    !byte 0x03
                    !byte 0x12
                    and (0x03,x)
                    !byte 0x03
                    !byte 0x03
                    ora 0x0303,x
                    asl 0x21
                    !byte 0x03
                    !byte 0x03
