datenschrott07
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0x00
                    !byte 0xdf
                    !byte 0x0c
                    ora 0x1e,x
                    !byte 0x27
                    bmi 0x305e
                    !byte 0x42
                    !byte 0x4b
                    !byte 0x54
                    eor 0x6f66,x
                    sei
                    sta (0x8a,x)
                    !byte 0x03
                    !byte 0x00
                    and 0x0e19,y
                    and 0x2a7f,x
                    rol
                    asl 0x1e1e,x
                    and 0x193d,x
                    !byte 0x2f
                    !byte 0x2f
                    !byte 0x39
                    ;and 0x20ea,y
                    ;sbc 0x2f,x
