                    bcs 0x0fa6
                    ror 0x9eed,x
                    !byte 0x02
                    !byte 0x53
                    lsr 0x11,x
                    asl 0x0beb
                    and 0x89
                    rol 0x18,x
                    ora 0x35d1
                    !byte 0x53
                    and 0x98
                    inc 0x265b
                    adc 0x45,x
                    sec
                    beq 0x0fd1
                    asl 0x45
                    rol 0x74
                    eor 0x86
                    !byte 0x34
                    !byte 0xda
                    !byte 0x23
                    and 0x7426,x
                    !byte 0x3b
                    !byte 0xb2
                    stx 0x34
                    !byte 0x92
                    !byte 0x43
